### PR TITLE
Chinese Language support

### PR DESCRIPTION
**Pull request by Punchwes**
1.added Chinese tokeniser(stanford coreNLP) and handle surrogate characters.
2.modified remove stopword function to accept two arguments(still compatible with previous usage) and added stopwords for Chinese.
3.update punctuation list to include Chinese punctuations and punctuation pattern regex match.
4.updated pom.xml.
5.added test samples in Util.java.
6.updated confighandler for Chinese tokeniser and stopwords.
7.updated version to 7.21.4

### CODE REVIEW

**Comment by simonwibberley** [comment]
Hi @Punchwes in TokenFilterRelevanceStopwords.java, a couple of things:
 - there seems to be two copies of the English stop word list, on as a 'dictionary' one as a list
 - the zh stop words seem to include the English ones

Could you verify whether this is expected?

**Comment by Punchwes** [comment]
Hi @simonwibberley , the first thing is that I noticed that the usage of directly calling getStopwords() after importing the TokenFilterRelevanceStopwords exists in Method52 code (does not create a new object, so no way to pass a lang parameter), such as in the `ClusterFeatures.java`:
```
import uk.ac.susx.tag.classificationframework.featureextraction.filtering.TokenFilterRelevanceStopwords;
...
...
return ClusterFeatureAnalysis.getTopPhrases(
		0,                  // cluster 0
		topFeatures,        // document features
		docs,               // documents to use
		pipeline,           // feature extraction pipeline
		new FeatureClusterJointCounter.HighestProbabilityOnly(),    // cluster membership
		phrases,            // number of phrases per feature
		threshold,          // min n+mgram threshold for overriding ngram
		count,                  // min occurences to be considered a phrase at all
		ng1,ng2,ng3,        // n+1 gram level thresholds for overriding ngram
		TokenFilterRelevanceStopwords.getStopwords(), // stopwords
		minPhraseLength,    // min phrase length
		maxPhraseLength);   // max phrase length
	}
```
I am afraid this kind of usage could be widely found in the codebase, so I choose not to change the getStopwords() method which still return **_current_** stopwords(English stopwords if not passing any lang param to create a new object) and add additional methods and the dictionary which enable language parameter. The reason I did not change the `getStopwords()` method so that it could just return `stopwords_dictionary.get("en")` or reset stopwords is that there are some additional methods in the class such as `filter()` and `getIndexedStopwords()` which directly call `getStopwords()` which could be current language specific. **_In the end_**, I choose to define a stopword list which contains current stopwords, and a dictionary which contains stopwords for each language, and I also define several methods so that it could change current stopwords(when creating a new object by `TokenFilterRelevanceStopwords(String lang)`) or simply obtain stopwords list given specific language parameter without creating new object(`getStopwords_dict(String lang)`). The `getStopwords()` will only be used to just obtain current stopwords(English stopwords in default).

The second one is that, it is quite common to find English words in Chinese document texts so most public Chinese stopword lists also contain some(I am not sure if all) English stopwords and typical English characters which is used in Chinese as meaningless symbols such as "zz" and "zt". So I just add the whole stopword list which is widely used for Chinese texts into the dictionary.

**Comment by simonwibberley** [comment]
Thanks for the explanation @Punchwes - I guess my real questions is : could we have one copy of the English stop word list and refer to it three times?

**Comment by simonwibberley** [comment]
Is the English part of the Chinese stop word list the same as the English one?

**Comment by simonwibberley** [comment]
It seems the main difference is that the English part of the Chinese one has contractions in it.

**Comment by simonwibberley** [comment]
I'm splitting hairs, the PR seems fine really.

**Comment by Punchwes** [comment]
Hi @simonwibberley , yes, there are some contractions between English stopwords and English words in Chinese stopwords, that is the reason I am not merging two lists(Chinese words and English stopwords) to create new Chinese stopwords.

**Pull request merged**
